---
knit: pagedown::chrome_print
output:
  pagedown::html_paged:
    self_contained: TRUE
    number_sections: FALSE
    fig_caption: TRUE
    css: ["css/simple-report-style.css", "css/simple-report-page.css", "css/simple-report-default.css"]
paged-footnotes: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      error = FALSE,
                      fig.topcaption = TRUE,
                      fig.cap = TRUE,
                      dpi = 150)
library(tidyverse)
library(flextable)
library(knitr)
library(omni)
library(scales)
library(santoku)
```



```{r}
text <- tibble(
  year = seq(2000, 2020, 1),
  long_text = "Laborum cupidatat velit dolor. Lorem minim enim id elit reprehenderit qui ea velit irure. Labore laborum anim eiusmod. Eiusmod cillum ad proident magna Lorem ipsum irure consectetur id ipsum sint ad occaecat nostrud. Amet aute fugiat nisi sunt cillum sunt irure. Duis laborum laboris ullamco proident aliquip incididunt id tempor exercitation velit ad nisi laboris do in. Exercitation tempor minim aute sint dolore duis voluptate. Duis consectetur adipisicing nostrud aliquip velit adipisicing officia sunt irure nostrud commodo consequat Lorem ipsum. Nisi proident ullamco elit esse amet qui duis ullamco. Duis aute aliqua laboris labore officia aliquip."
)
```

# Bad Multipage Table

This breaks weird across tables.

```{r}
text %>% 
  flextable()
```

\newpage

# Good Multipage Tables

But this doesn't!

```{r eval = FALSE}
df <- text
max_table_height <- 4

table <- text %>% 
  omni::omni_table("test", use_image = FALSE)

table_dimensions <- table %>%
  dim_pretty()

table_row_heights <- table_dimensions$heights %>%
  as_tibble() %>% 
  # Remove header
  slice(-1) 
%>% 
  set_names("row_height") %>%
  mutate(row_id = row_number()) %>%
  mutate(cumulative_height = cumsum(row_height)) %>%
  mutate(total_height = max(cumulative_height)) %>% 
  mutate(table_number = kiru(cumulative_height,
                             breaks = seq(0, max(.$total_height), max_table_height))) %>% 
  mutate(table_number = as.numeric(table_number)) 
```





```{r results='asis'}
multipage_table <- function(df, max_table_height = 1) {
  
  add_table_numbers <- function(df) {
    
    table <- df %>% 
      flextable()
    
    table_dimensions <- table %>%
      dim_pretty()
    
    table_row_heights <- table_dimensions$heights %>%
      as_tibble() %>% 
      # Remove header
      slice(-1) %>% 
      set_names("row_height") %>%
      mutate(row_id = row_number()) %>%
      mutate(cumulative_height = cumsum(row_height)) %>%
      mutate(total_height = max(cumulative_height)) %>% 
      mutate(table_number = kiru(cumulative_height,
                                 breaks = seq(0, max(.$total_height), max_table_height))) %>% 
      mutate(table_number = as.numeric(table_number)) 
  
    text_with_table_number <- df %>% 
      bind_cols(table_row_heights) %>% 
      select(year, long_text, table_number, row_height, cumulative_height, total_height)
    
    text_with_table_number
    
  }
  
  text_with_table_numbers <- add_table_numbers(text)
  
  tables <- text_with_table_numbers %>% 
    distinct(table_number) %>% 
    pull(table_number)
  
  display_single_table <- function(table_number_to_filter) {
    
    table_to_print <- text_with_table_numbers %>% 
      filter(table_number == table_number_to_filter) %>% 
      select(-c(table_number:total_height)) %>% 
      flextable()
    
    flextable_to_rmd(table_to_print)
    
    cat("\\newpage")
    
  }
  
  walk(tables, display_single_table)
  
}
```

```{r}
text %>% 
  slice(1:2) %>% 
  multipage_table()
```


```{r results='asis'}
multipage_table(text, max_table_height = 1.25)
```




